version: '1.0.0-{branch}.{build}'

pull_requests:
  do_not_increment_build_number: true

configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '1.0.0'
  assembly_file_version: '1.0.0'
  assembly_informational_version: '{version}'

before_build:
- cmd: nuget restore

build:
  verbosity: minimal

artifacts:
- path: Pretzel.IncludeExtras\bin\$(configuration)\Pretzel.IncludeExtras.dll
  name: Pretzel.IncludeExtras.dll